name: Caunnr CI
on:
  - pull_request

jobs:
  phpinsights:
    runs-on: ubuntu-latest
    name: PHP Insights checks
    steps:
      - name: Run Insights Checks
        uses: actions/checkout@v2
        uses: shivammathur/setup-php@v1
        with:
          php-version: 7.3
      - run: composer install --prefer-dist --no-progress --no-suggest
      - run: vendor/bin/phpinsights -n --ansi --format=github-action
      - name: Add labels to PRs
        uses: "srvaroa/labeler@master"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
