name: Caunnr Label PRs

on: [pull_request]

jobs:
  label-pr:
		runs-on: ubuntu-latest
		steps:
			- name: Add labels
				uses: srvaroa/labeler@master
				env:
					GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
